- name: Copy rpm file to server
  copy:
     src: test-task-0.0.1-1.el7.noarch.rpm
     dest: /home/user/

- name: Install package.
  yum:
     name: /home/user/test-task-0.0.1-1.el7.noarch.rpm
     state: present

- name: Set variables
  ansible.builtin.shell: message=['message']

